config: disable build of NXP PFE PMD Driver on ARM
Enabling build of this library causes compilation error on ARM:
/usr/bin/ld: cannot find -lrte_common_dpaax
collect2: error: ld returned 1 exit status
/scratch/spdk/dpdk/mk/rte.app.mk:433: recipe for target 'cmdline_test' failed
NXP PFE PMD drivers requires librte_common_dpaax which is not built by default.
Passing CONFIG_RTE_LIBRTE_PFE_PMD=n to dpdpk Makefile has no effect since
this is overwritten by the config file.

Change-Id: I3fc4822804d0e649c838028a670562fba3f08479
Reviewed-on: https://review.gerrithub.io/c/spdk/dpdk/+/481562 (spdk-19.11)
Signed-off-by: Alexey Marchuk <alexeymar@mellanox.com>
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/dpdk/+/2533
Reviewed-by: Ben Walker <benjamin.walker@intel.com>
Reviewed-by: Darek Stojaczyk <dariusz.stojaczyk@intel.com>
Tested-by: Ben Walker <benjamin.walker@intel.com>