config: disable librte_vhost
SPDK carries its own copy of the vhost library, so we don't need to
build the DPDK version.

Additionally, the DPDK version of librte_vhost fails to compile with the
system compiler on CentOS 6 (gcc 4.4.7):

  dpdk/lib/librte_vhost/iotlb.c: In function ‘vhost_user_iotlb_pending_insert’:
  include/rte_mempool.h:1288: error: dereferencing pointer ‘obj_p’ does break strict-aliasing rules
  lib/librte_vhost/iotlb.c:96: note: initialized from here

Change-Id: Ie25c3229adbda184b8828701b8148626a30809a9
Signed-off-by: Daniel Verkamp <daniel.verkamp@intel.com>