net/mlx5: fix build with separate glue lib for dlopen
If building with option RTE_IBVERBS_LINK_DLOPEN (make)
or ibverbs_link=dlopen (meson), the glue is a separate library
which can be dlopen.
In such case, the object mlx5_glue must be allocated in two places:
one in the glue, and one outside of the glue to be assigned when
loading the glue with dlopen/dlsym.

When backporting the allocation split for gcc 10, both allocations
were made inside the glue. As a consequence, the symbol is undefined
outside of the glue:
	drivers/net/mlx5/mlx5.c: undefined reference to 'mlx5_glue'

The second allocation is restored outside of the glue, in mlx5.c.

Fixes: b3e01cd3e46f ("common/mlx5: fix build with -fno-common")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: Luca Boccassi <bluca@debian.org>